//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 08:45:21 AM GMT 
//


package com.rjc.sportfiles.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rjc.sportfiles.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rjc.sportfiles.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase }
     * 
     */
    public TrainingCenterDatabase createTrainingCenterDatabase() {
        return new TrainingCenterDatabase();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Author }
     * 
     */
    public TrainingCenterDatabase.Author createTrainingCenterDatabaseAuthor() {
        return new TrainingCenterDatabase.Author();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Author.Build }
     * 
     */
    public TrainingCenterDatabase.Author.Build createTrainingCenterDatabaseAuthorBuild() {
        return new TrainingCenterDatabase.Author.Build();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities }
     * 
     */
    public TrainingCenterDatabase.Activities createTrainingCenterDatabaseActivities() {
        return new TrainingCenterDatabase.Activities();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity createTrainingCenterDatabaseActivitiesActivity() {
        return new TrainingCenterDatabase.Activities.Activity();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Creator }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Creator createTrainingCenterDatabaseActivitiesActivityCreator() {
        return new TrainingCenterDatabase.Activities.Activity.Creator();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Lap }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Lap createTrainingCenterDatabaseActivitiesActivityLap() {
        return new TrainingCenterDatabase.Activities.Activity.Lap();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Lap.Track }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Lap.Track createTrainingCenterDatabaseActivitiesActivityLapTrack() {
        return new TrainingCenterDatabase.Activities.Activity.Lap.Track();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint createTrainingCenterDatabaseActivitiesActivityLapTrackTrackpoint() {
        return new TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint();
    }

    /**
     * Create an instance of {@link TPX }
     * 
     */
    public TPX createTPX() {
        return new TPX();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Author.Build.Version }
     * 
     */
    public TrainingCenterDatabase.Author.Build.Version createTrainingCenterDatabaseAuthorBuildVersion() {
        return new TrainingCenterDatabase.Author.Build.Version();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Creator.Version }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Creator.Version createTrainingCenterDatabaseActivitiesActivityCreatorVersion() {
        return new TrainingCenterDatabase.Activities.Activity.Creator.Version();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm createTrainingCenterDatabaseActivitiesActivityLapTrackTrackpointHeartRateBpm() {
        return new TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions }
     * 
     */
    public TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions createTrainingCenterDatabaseActivitiesActivityLapTrackTrackpointExtensions() {
        return new TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions();
    }

}
