//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 08:45:21 AM GMT 
//


package com.rjc.sportfiles.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Activities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Activity">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="Lap" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TotalTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="MaximumSpeed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="Calories" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="Intensity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TriggerMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Track">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Trackpoint" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                           &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                           &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                           &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="HeartRateBpm">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="Extensions">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Creator">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="Version">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                 &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                 &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                 &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Sport" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Author">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Build">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Version">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LangID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activities",
    "author"
})
@XmlRootElement(name = "TrainingCenterDatabase")
public class TrainingCenterDatabase {

    @XmlElement(name = "Activities", required = true)
    protected TrainingCenterDatabase.Activities activities;
    @XmlElement(name = "Author", required = true)
    protected TrainingCenterDatabase.Author author;

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link TrainingCenterDatabase.Activities }
     *     
     */
    public TrainingCenterDatabase.Activities getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainingCenterDatabase.Activities }
     *     
     */
    public void setActivities(TrainingCenterDatabase.Activities value) {
        this.activities = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link TrainingCenterDatabase.Author }
     *     
     */
    public TrainingCenterDatabase.Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainingCenterDatabase.Author }
     *     
     */
    public void setAuthor(TrainingCenterDatabase.Author value) {
        this.author = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Activity">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="Lap" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TotalTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="MaximumSpeed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="Calories" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="Intensity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TriggerMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Track">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Trackpoint" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                                 &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                                 &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                                 &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="HeartRateBpm">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="Extensions">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Creator">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="Version">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                       &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                       &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                       &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Sport" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activity"
    })
    public static class Activities {

        @XmlElement(name = "Activity", required = true)
        protected TrainingCenterDatabase.Activities.Activity activity;

        /**
         * Gets the value of the activity property.
         * 
         * @return
         *     possible object is
         *     {@link TrainingCenterDatabase.Activities.Activity }
         *     
         */
        public TrainingCenterDatabase.Activities.Activity getActivity() {
            return activity;
        }

        /**
         * Sets the value of the activity property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrainingCenterDatabase.Activities.Activity }
         *     
         */
        public void setActivity(TrainingCenterDatabase.Activities.Activity value) {
            this.activity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="Lap" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TotalTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="MaximumSpeed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="Calories" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="Intensity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TriggerMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Track">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Trackpoint" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                                       &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                                       &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                                       &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="HeartRateBpm">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                       &lt;element name="Extensions">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Creator">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="Version">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                             &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                             &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                             &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Sport" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "lap",
            "creator"
        })
        public static class Activity {

            @XmlElement(name = "Id", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar id;
            @XmlElement(name = "Lap", required = true)
            protected List<TrainingCenterDatabase.Activities.Activity.Lap> lap;
            @XmlElement(name = "Creator", required = true)
            protected TrainingCenterDatabase.Activities.Activity.Creator creator;
            @XmlAttribute(name = "Sport", required = true)
            protected String sport;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setId(XMLGregorianCalendar value) {
                this.id = value;
            }

            /**
             * Gets the value of the lap property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the lap property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLap().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TrainingCenterDatabase.Activities.Activity.Lap }
             * 
             * 
             */
            public List<TrainingCenterDatabase.Activities.Activity.Lap> getLap() {
                if (lap == null) {
                    lap = new ArrayList<TrainingCenterDatabase.Activities.Activity.Lap>();
                }
                return this.lap;
            }

            /**
             * Gets the value of the creator property.
             * 
             * @return
             *     possible object is
             *     {@link TrainingCenterDatabase.Activities.Activity.Creator }
             *     
             */
            public TrainingCenterDatabase.Activities.Activity.Creator getCreator() {
                return creator;
            }

            /**
             * Sets the value of the creator property.
             * 
             * @param value
             *     allowed object is
             *     {@link TrainingCenterDatabase.Activities.Activity.Creator }
             *     
             */
            public void setCreator(TrainingCenterDatabase.Activities.Activity.Creator value) {
                this.creator = value;
            }

            /**
             * Gets the value of the sport property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSport() {
                return sport;
            }

            /**
             * Sets the value of the sport property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSport(String value) {
                this.sport = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="Version">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                   &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                   &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                   &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "productID",
                "version"
            })
            public static class Creator {

                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "ProductID")
                @XmlSchemaType(name = "unsignedByte")
                protected short productID;
                @XmlElement(name = "Version", required = true)
                protected TrainingCenterDatabase.Activities.Activity.Creator.Version version;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the productID property.
                 * 
                 */
                public short getProductID() {
                    return productID;
                }

                /**
                 * Sets the value of the productID property.
                 * 
                 */
                public void setProductID(short value) {
                    this.productID = value;
                }

                /**
                 * Gets the value of the version property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TrainingCenterDatabase.Activities.Activity.Creator.Version }
                 *     
                 */
                public TrainingCenterDatabase.Activities.Activity.Creator.Version getVersion() {
                    return version;
                }

                /**
                 * Sets the value of the version property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TrainingCenterDatabase.Activities.Activity.Creator.Version }
                 *     
                 */
                public void setVersion(TrainingCenterDatabase.Activities.Activity.Creator.Version value) {
                    this.version = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *         &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *         &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *         &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "versionMajor",
                    "versionMinor",
                    "buildMajor",
                    "buildMinor"
                })
                public static class Version {

                    @XmlElement(name = "VersionMajor")
                    @XmlSchemaType(name = "unsignedByte")
                    protected short versionMajor;
                    @XmlElement(name = "VersionMinor")
                    @XmlSchemaType(name = "unsignedByte")
                    protected short versionMinor;
                    @XmlElement(name = "BuildMajor")
                    @XmlSchemaType(name = "unsignedByte")
                    protected short buildMajor;
                    @XmlElement(name = "BuildMinor")
                    @XmlSchemaType(name = "unsignedByte")
                    protected short buildMinor;

                    /**
                     * Gets the value of the versionMajor property.
                     * 
                     */
                    public short getVersionMajor() {
                        return versionMajor;
                    }

                    /**
                     * Sets the value of the versionMajor property.
                     * 
                     */
                    public void setVersionMajor(short value) {
                        this.versionMajor = value;
                    }

                    /**
                     * Gets the value of the versionMinor property.
                     * 
                     */
                    public short getVersionMinor() {
                        return versionMinor;
                    }

                    /**
                     * Sets the value of the versionMinor property.
                     * 
                     */
                    public void setVersionMinor(short value) {
                        this.versionMinor = value;
                    }

                    /**
                     * Gets the value of the buildMajor property.
                     * 
                     */
                    public short getBuildMajor() {
                        return buildMajor;
                    }

                    /**
                     * Sets the value of the buildMajor property.
                     * 
                     */
                    public void setBuildMajor(short value) {
                        this.buildMajor = value;
                    }

                    /**
                     * Gets the value of the buildMinor property.
                     * 
                     */
                    public short getBuildMinor() {
                        return buildMinor;
                    }

                    /**
                     * Sets the value of the buildMinor property.
                     * 
                     */
                    public void setBuildMinor(short value) {
                        this.buildMinor = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TotalTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="MaximumSpeed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="Calories" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="Intensity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TriggerMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Track">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Trackpoint" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                             &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                             &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                             &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="HeartRateBpm">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                             &lt;element name="Extensions">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "totalTimeSeconds",
                "distanceMeters",
                "maximumSpeed",
                "calories",
                "intensity",
                "triggerMethod",
                "track"
            })
            public static class Lap {

                @XmlElement(name = "TotalTimeSeconds", required = true)
                protected BigDecimal totalTimeSeconds;
                @XmlElement(name = "DistanceMeters", required = true)
                protected BigDecimal distanceMeters;
                @XmlElement(name = "MaximumSpeed", required = true)
                protected BigDecimal maximumSpeed;
                @XmlElement(name = "Calories")
                @XmlSchemaType(name = "unsignedByte")
                protected short calories;
                @XmlElement(name = "Intensity", required = true)
                protected String intensity;
                @XmlElement(name = "TriggerMethod", required = true)
                protected String triggerMethod;
                @XmlElement(name = "Track", required = true)
                protected TrainingCenterDatabase.Activities.Activity.Lap.Track track;
                @XmlAttribute(name = "StartTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar startTime;

                /**
                 * Gets the value of the totalTimeSeconds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getTotalTimeSeconds() {
                    return totalTimeSeconds;
                }

                /**
                 * Sets the value of the totalTimeSeconds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setTotalTimeSeconds(BigDecimal value) {
                    this.totalTimeSeconds = value;
                }

                /**
                 * Gets the value of the distanceMeters property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getDistanceMeters() {
                    return distanceMeters;
                }

                /**
                 * Sets the value of the distanceMeters property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setDistanceMeters(BigDecimal value) {
                    this.distanceMeters = value;
                }

                /**
                 * Gets the value of the maximumSpeed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getMaximumSpeed() {
                    return maximumSpeed;
                }

                /**
                 * Sets the value of the maximumSpeed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setMaximumSpeed(BigDecimal value) {
                    this.maximumSpeed = value;
                }

                /**
                 * Gets the value of the calories property.
                 * 
                 */
                public short getCalories() {
                    return calories;
                }

                /**
                 * Sets the value of the calories property.
                 * 
                 */
                public void setCalories(short value) {
                    this.calories = value;
                }

                /**
                 * Gets the value of the intensity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIntensity() {
                    return intensity;
                }

                /**
                 * Sets the value of the intensity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIntensity(String value) {
                    this.intensity = value;
                }

                /**
                 * Gets the value of the triggerMethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTriggerMethod() {
                    return triggerMethod;
                }

                /**
                 * Sets the value of the triggerMethod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTriggerMethod(String value) {
                    this.triggerMethod = value;
                }

                /**
                 * Gets the value of the track property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track }
                 *     
                 */
                public TrainingCenterDatabase.Activities.Activity.Lap.Track getTrack() {
                    return track;
                }

                /**
                 * Sets the value of the track property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track }
                 *     
                 */
                public void setTrack(TrainingCenterDatabase.Activities.Activity.Lap.Track value) {
                    this.track = value;
                }

                /**
                 * Gets the value of the startTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getStartTime() {
                    return startTime;
                }

                /**
                 * Sets the value of the startTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setStartTime(XMLGregorianCalendar value) {
                    this.startTime = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Trackpoint" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *                   &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *                   &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *                   &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="HeartRateBpm">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                   &lt;element name="Extensions">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "trackpoint"
                })
                public static class Track {

                    @XmlElement(name = "Trackpoint", required = true)
                    protected List<TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint> trackpoint;

                    /**
                     * Gets the value of the trackpoint property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the trackpoint property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getTrackpoint().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint }
                     * 
                     * 
                     */
                    public List<TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint> getTrackpoint() {
                        if (trackpoint == null) {
                            trackpoint = new ArrayList<TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint>();
                        }
                        return this.trackpoint;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                     *         &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                     *         &lt;element name="Cadence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                     *         &lt;element name="SensorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="HeartRateBpm">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *         &lt;element name="Extensions">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "time",
                        "distanceMeters",
                        "cadence",
                        "sensorState",
                        "heartRateBpm",
                        "extensions"
                    })
                    public static class Trackpoint {

                        @XmlElement(name = "Time", required = true)
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar time;
                        @XmlElement(name = "DistanceMeters", required = true)
                        protected BigDecimal distanceMeters;
                        @XmlElement(name = "Cadence")
                        @XmlSchemaType(name = "unsignedByte")
                        protected short cadence;
                        @XmlElement(name = "SensorState", required = true)
                        protected String sensorState;
                        @XmlElement(name = "HeartRateBpm", required = true)
                        protected TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm heartRateBpm;
                        @XmlElement(name = "Extensions", required = true)
                        protected TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions extensions;

                        /**
                         * Gets the value of the time property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getTime() {
                            return time;
                        }

                        /**
                         * Sets the value of the time property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setTime(XMLGregorianCalendar value) {
                            this.time = value;
                        }

                        /**
                         * Gets the value of the distanceMeters property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public BigDecimal getDistanceMeters() {
                            return distanceMeters;
                        }

                        /**
                         * Sets the value of the distanceMeters property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public void setDistanceMeters(BigDecimal value) {
                            this.distanceMeters = value;
                        }

                        /**
                         * Gets the value of the cadence property.
                         * 
                         */
                        public short getCadence() {
                            return cadence;
                        }

                        /**
                         * Sets the value of the cadence property.
                         * 
                         */
                        public void setCadence(short value) {
                            this.cadence = value;
                        }

                        /**
                         * Gets the value of the sensorState property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSensorState() {
                            return sensorState;
                        }

                        /**
                         * Sets the value of the sensorState property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSensorState(String value) {
                            this.sensorState = value;
                        }

                        /**
                         * Gets the value of the heartRateBpm property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm }
                         *     
                         */
                        public TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm getHeartRateBpm() {
                            return heartRateBpm;
                        }

                        /**
                         * Sets the value of the heartRateBpm property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm }
                         *     
                         */
                        public void setHeartRateBpm(TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.HeartRateBpm value) {
                            this.heartRateBpm = value;
                        }

                        /**
                         * Gets the value of the extensions property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions }
                         *     
                         */
                        public TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions getExtensions() {
                            return extensions;
                        }

                        /**
                         * Sets the value of the extensions property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions }
                         *     
                         */
                        public void setExtensions(TrainingCenterDatabase.Activities.Activity.Lap.Track.Trackpoint.Extensions value) {
                            this.extensions = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element ref="{http://www.garmin.com/xmlschemas/ActivityExtension/v2}TPX"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "tpx"
                        })
                        public static class Extensions {

                            @XmlElement(name = "TPX", namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2", required = true)
                            protected TPX tpx;

                            /**
                             * Gets the value of the tpx property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link TPX }
                             *     
                             */
                            public TPX getTPX() {
                                return tpx;
                            }

                            /**
                             * Sets the value of the tpx property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link TPX }
                             *     
                             */
                            public void setTPX(TPX value) {
                                this.tpx = value;
                            }

                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class HeartRateBpm {

                            @XmlElement(name = "Value")
                            @XmlSchemaType(name = "unsignedByte")
                            protected short value;

                            /**
                             * Gets the value of the value property.
                             * 
                             */
                            public short getValue() {
                                return value;
                            }

                            /**
                             * Sets the value of the value property.
                             * 
                             */
                            public void setValue(short value) {
                                this.value = value;
                            }

                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Build">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Version">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LangID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "build",
        "langID"
    })
    public static class Author {

        @XmlElement(name = "Name", required = true)
        protected Object name;
        @XmlElement(name = "Build", required = true)
        protected TrainingCenterDatabase.Author.Build build;
        @XmlElement(name = "LangID", required = true)
        protected String langID;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setName(Object value) {
            this.name = value;
        }

        /**
         * Gets the value of the build property.
         * 
         * @return
         *     possible object is
         *     {@link TrainingCenterDatabase.Author.Build }
         *     
         */
        public TrainingCenterDatabase.Author.Build getBuild() {
            return build;
        }

        /**
         * Sets the value of the build property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrainingCenterDatabase.Author.Build }
         *     
         */
        public void setBuild(TrainingCenterDatabase.Author.Build value) {
            this.build = value;
        }

        /**
         * Gets the value of the langID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLangID() {
            return langID;
        }

        /**
         * Sets the value of the langID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLangID(String value) {
            this.langID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Version">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "version"
        })
        public static class Build {

            @XmlElement(name = "Version", required = true)
            protected TrainingCenterDatabase.Author.Build.Version version;

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link TrainingCenterDatabase.Author.Build.Version }
             *     
             */
            public TrainingCenterDatabase.Author.Build.Version getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link TrainingCenterDatabase.Author.Build.Version }
             *     
             */
            public void setVersion(TrainingCenterDatabase.Author.Build.Version value) {
                this.version = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="VersionMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="VersionMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="BuildMajor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="BuildMinor" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "versionMajor",
                "versionMinor",
                "buildMajor",
                "buildMinor"
            })
            public static class Version {

                @XmlElement(name = "VersionMajor")
                @XmlSchemaType(name = "unsignedByte")
                protected short versionMajor;
                @XmlElement(name = "VersionMinor")
                @XmlSchemaType(name = "unsignedByte")
                protected short versionMinor;
                @XmlElement(name = "BuildMajor")
                @XmlSchemaType(name = "unsignedByte")
                protected short buildMajor;
                @XmlElement(name = "BuildMinor")
                @XmlSchemaType(name = "unsignedByte")
                protected short buildMinor;

                /**
                 * Gets the value of the versionMajor property.
                 * 
                 */
                public short getVersionMajor() {
                    return versionMajor;
                }

                /**
                 * Sets the value of the versionMajor property.
                 * 
                 */
                public void setVersionMajor(short value) {
                    this.versionMajor = value;
                }

                /**
                 * Gets the value of the versionMinor property.
                 * 
                 */
                public short getVersionMinor() {
                    return versionMinor;
                }

                /**
                 * Sets the value of the versionMinor property.
                 * 
                 */
                public void setVersionMinor(short value) {
                    this.versionMinor = value;
                }

                /**
                 * Gets the value of the buildMajor property.
                 * 
                 */
                public short getBuildMajor() {
                    return buildMajor;
                }

                /**
                 * Sets the value of the buildMajor property.
                 * 
                 */
                public void setBuildMajor(short value) {
                    this.buildMajor = value;
                }

                /**
                 * Gets the value of the buildMinor property.
                 * 
                 */
                public short getBuildMinor() {
                    return buildMinor;
                }

                /**
                 * Sets the value of the buildMinor property.
                 * 
                 */
                public void setBuildMinor(short value) {
                    this.buildMinor = value;
                }

            }

        }

    }

}
